# Generated by Django 6.1 on 2026-08-19 17:39

import datetime
import django.db.models.deletion
import doc.models
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0001_initial'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wagtailcore', '0097_baselogentry_uuid_action_timestamp_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('meeting_date', models.DateField(verbose_name='Datum jednání')),
                ('meeting_time', models.TimeField(default=datetime.time(19, 0), verbose_name='Začátek')),
                ('location', models.CharField(blank=True, default='sborovna v hlavní budově', max_length=255, verbose_name='Místo konání')),
                ('participants', wagtail.fields.StreamField([('participant', 3)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._vr_member_choices, 'label': 'Člen VR'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._other_member_choices, 'label': 'Jiný člen'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Jiná osoba', 'max_length': 255}), 3: ('wagtail.blocks.StreamBlock', [[('vr_member', 0), ('member', 1), ('other', 2)]], {})}, default=doc.models._default_participants, verbose_name='Seznam účastníků')),
                ('items', wagtail.fields.StreamField([('item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Název bodu', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._vr_member_choices, 'label': 'Člen VR'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._other_member_choices, 'label': 'Jiný člen'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Jiná osoba', 'max_length': 255}), 4: ('wagtail.blocks.StreamBlock', [[('vr_member', 1), ('member', 2), ('other', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'label': 'Předkládá', 'min_num': 1}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Popis', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Výstup', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('presenter', 5), ('body', 6), ('outcome', 7)]], {})}, verbose_name='Body programu')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AgendaPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='doc.agendapage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agendapage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='doc.AgendaPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
