# Generated by Django 6.1 on 2026-09-17 16:10

import doc.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_seed_zaklady_soukromi_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapage',
            name='items',
            field=wagtail.fields.StreamField([('item', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Název bodu', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._vr_member_choices, 'label': 'Člen VR'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._other_member_choices, 'label': 'Jiný člen'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Jiná osoba', 'max_length': 255}), 4: ('wagtail.blocks.StreamBlock', [[('vr_member', 1), ('member', 2), ('other', 3)]], {'label': 'Předkládá', 'min_num': 1}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Popis', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Výstup', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('heading', 0), ('presenter', 4), ('body', 5), ('outcome', 6)]], {})}, verbose_name='Body programu'),
        ),
        migrations.AlterField(
            model_name='agendapage',
            name='participants',
            field=wagtail.fields.StreamField([('vr_member', 0), ('member', 1), ('other', 2)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._vr_member_choices, 'label': 'Člen VR'}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._other_member_choices, 'label': 'Jiný člen'}), 2: ('wagtail.blocks.CharBlock', (), {'label': 'Jiná osoba', 'max_length': 255})}, default=doc.models._default_participants, verbose_name='Seznam účastníků'),
        ),
    ]
