# Generated by Django 6.1 on 2026-09-23 17:14

import doc.models
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0004_alter_agendapage_items_alter_agendapage_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendapage',
            name='items',
            field=wagtail.fields.StreamField([('item', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Název bodu', 'max_length': 255}), 1: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._vr_member_choices, 'label': 'Člen VR'}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': doc.models._other_member_choices, 'label': 'Jiný člen'}), 3: ('wagtail.blocks.CharBlock', (), {'label': 'Jiná osoba', 'max_length': 255}), 4: ('wagtail.blocks.StreamBlock', [[('vr_member', 1), ('member', 2), ('other', 3)]], {'label': 'Předkládá', 'min_num': 1}), 5: ('wagtail.blocks.RichTextBlock', (), {'label': 'Popis', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'label': 'Debata', 'required': False}), 7: ('wagtail.blocks.RichTextBlock', (), {'label': 'Výstup', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('heading', 0), ('presenter', 4), ('item', 5), ('discussion', 6), ('outcome', 7)]], {})}, verbose_name='Body programu'),
        ),
    ]
