# Generated by Django 6.0.4 on 2026-04-28 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Pravidlo')),
                ('variant', models.IntegerField(blank=True, choices=[(1, 'jedno dítě'), (2, 'sourozenec'), (3, 'druhý sourozenec')], null=True)),
                ('valid_from', models.DateField(auto_now=True, null=True, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
            ],
        ),
    ]
