# Generated by Django 6.0.4 on 2026-05-26 22:23

import django.core.validators
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Jméno")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Příjmení"),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True,
                        validators=[main.models.validuj_datum_narozeni],
                        verbose_name="Datum narození",
                    ),
                ),
                (
                    "rc_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        verbose_name="Otisk rodného čísla",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region="CZ", verbose_name="Telefon"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Člen spolku",
                "verbose_name_plural": "Členové spolku",
            },
        ),
        migrations.CreateModel(
            name="ClassCollective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=2026,
                        validators=[
                            django.core.validators.MinValueValidator(2000),
                            django.core.validators.MaxValueValidator(2100),
                        ],
                        verbose_name="Rok nástupu",
                    ),
                ),
                (
                    "school_class",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1. ročník"),
                            (2, "2. ročník"),
                            (3, "3. ročník"),
                            (4, "4. ročník"),
                            (5, "5. ročník"),
                            (6, "6. ročník"),
                            (7, "7. ročník"),
                            (8, "8. ročník"),
                            (9, "9. ročník"),
                        ],
                        null=True,
                    ),
                ),
                ("variant", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "verbose_name": "Třídna",
                "verbose_name_plural": "Třídy",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "variant"), name="unique_class_collective_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParentRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "valid_from",
                    models.DateField(auto_now=True, verbose_name="Platnost od"),
                ),
                (
                    "valid_until",
                    models.DateField(blank=True, null=True, verbose_name="Platnost do"),
                ),
                (
                    "paring_info",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Infromace o žákovi",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Jméno")),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Příjmení"),
                ),
                (
                    "rc_hash",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Otisk rodného čísla",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(
                        related_name="children",
                        through="main.ParentRelationship",
                        to="main.profile",
                        verbose_name="Zákonní zástupci",
                    ),
                ),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="main.classcollective",
                        verbose_name="Třída",
                    ),
                ),
            ],
            options={
                "verbose_name": "Žák",
                "verbose_name_plural": "Žáci",
            },
        ),
        migrations.AddField(
            model_name="parentrelationship",
            name="student",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.student",
            ),
        ),
        migrations.AddConstraint(
            model_name="parentrelationship",
            constraint=models.UniqueConstraint(
                fields=("student", "parent"), name="student_parent_unique"
            ),
        ),
    ]
