# Generated by Django 6.0.4 on 2026-04-28 01:51

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.IntegerField(blank=True, choices=[(1, '1. ročník'), (2, '2. ročník'), (3, '3. ročník'), (4, '4. ročník'), (5, '5. ročník'), (6, '6. ročník'), (7, '7. ročník'), (8, '8. ročník'), (9, '9. ročník')], null=True)),
                ('year', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Školní rok (nástupu)')),
                ('variant', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('year', 'variant'), name='unique_class_collective_name')],
            },
        ),
        migrations.CreateModel(
            name='CollectiveRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(auto_now=True, null=True, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.classcollective')),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='CZ', verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Zákoný zástupce',
                'verbose_name_plural': 'Zákonní zástupci',
            },
        ),
        migrations.CreateModel(
            name='ParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(auto_now=True, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('parents', models.ManyToManyField(related_name='children', through='main.ParentRelationship', to='main.parent', verbose_name='Rodiče')),
                ('school_class', models.ManyToManyField(related_name='students', through='main.CollectiveRelationship', to='main.classcollective', verbose_name='Třída')),
            ],
            options={
                'verbose_name': 'Žák',
                'verbose_name_plural': 'Žáci',
            },
        ),
        migrations.AddField(
            model_name='parentrelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AddField(
            model_name='collectiverelationship',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AddConstraint(
            model_name='parentrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='student_parent_unique'),
        ),
        migrations.AddConstraint(
            model_name='collectiverelationship',
            constraint=models.UniqueConstraint(fields=('student', 'school_class'), name='student_trida_unique_relationship'),
        ),
    ]
