# Generated by Django 6.0.6 on 2026-07-22 19:43

import django.core.validators
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCollective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok nástupu')),
                ('school_class', models.IntegerField(blank=True, choices=[(1, '1. ročník'), (2, '2. ročník'), (3, '3. ročník'), (4, '4. ročník'), (5, '5. ročník'), (6, '6. ročník'), (7, '7. ročník'), (8, '8. ročník'), (9, '9. ročník')], null=True)),
                ('variant', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Třídna',
                'verbose_name_plural': 'Třídy',
                'constraints': [models.UniqueConstraint(fields=('year', 'variant'), name='unique_class_collective_name')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[main.models.validuj_datum_narozeni], verbose_name='Datum narození')),
                ('street_and_number', models.CharField(max_length=150, verbose_name='Ulice a číslo popisné')),
                ('city', models.CharField(max_length=100, verbose_name='Město')),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zadejte platné PSČ ve formátu 123 45 nebo 12345.', regex='^\\d{3}\\s?\\d{2}$')], verbose_name='PSČ')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefonní číslo')),
                ('membership', models.CharField(choices=[('A', 'aktivní'), ('P', 'přispívající')], default='A', max_length=2)),
                ('status', models.CharField(choices=[('PE', 'čeká na schválení'), ('AC', 'člen'), ('CA', 'zrušený')], default='PE', max_length=2)),
                ('comments', models.TextField(blank=True, verbose_name='Poznámky')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet')),
            ],
            options={
                'verbose_name': 'Člen spolku',
                'verbose_name_plural': 'Členové spolku',
            },
        ),
        migrations.CreateModel(
            name='ParentRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(auto_now=True, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
                ('paring_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='Infromace o žákovi')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('birth_date', models.DateField(verbose_name='Datum narození')),
                ('parents', models.ManyToManyField(related_name='children', through='main.ParentRelationship', to='main.profile', verbose_name='Zákonní zástupci')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.classcollective', verbose_name='Třída')),
            ],
            options={
                'verbose_name': 'Žák',
                'verbose_name_plural': 'Žáci',
            },
        ),
        migrations.CreateModel(
            name='ProfileStudentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('A', 'přidat dítě')], default='A', max_length=2)),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno dítěte')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení dítěte')),
                ('birth_date', models.DateField(verbose_name='Datum narození dítěte')),
                ('comments', models.TextField(blank=True, verbose_name='Poznámky')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile')),
                ('student_by_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student', verbose_name='Žák (ověřeno jménem a datem narození)')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileMergeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PE', 'čeká na schválení'), ('AP', 'schváleno'), ('RE', 'zamítnuto')], default='PE', max_length=2)),
                ('old_email', models.EmailField(max_length=254, verbose_name='Stávající email')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno dítěte')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení dítěte')),
                ('birth_date', models.DateField(verbose_name='Datum narození dítěte')),
                ('comments', models.TextField(blank=True, verbose_name='Poznámky')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_by_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student', verbose_name='Žák (ověřeno jménem a datem narození)')),
            ],
        ),
        migrations.AddField(
            model_name='parentrelationship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AddConstraint(
            model_name='parentrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='student_parent_unique'),
        ),
    ]
