# Generated by Django 6.0.6 on 2026-07-24 05:05

import django.core.validators
import django.db.models.deletion
import main.models
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalClassCollective',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('year', models.PositiveIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Rok nástupu')),
                ('school_class', models.IntegerField(blank=True, choices=[(1, '1. ročník'), (2, '2. ročník'), (3, '3. ročník'), (4, '4. ročník'), (5, '5. ročník'), (6, '6. ročník'), (7, '7. ročník'), (8, '8. ročník'), (9, '9. ročník')], null=True)),
                ('variant', models.CharField(blank=True, max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Třídna',
                'verbose_name_plural': 'historical Třídy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalProfile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('birth_date', models.DateField(validators=[main.models.validuj_datum_narozeni], verbose_name='Datum narození')),
                ('street_and_number', models.CharField(max_length=150, verbose_name='Ulice a číslo popisné')),
                ('city', models.CharField(max_length=100, verbose_name='Město')),
                ('zip_code', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Zadejte platné PSČ ve formátu 123 45 nebo 12345.', regex='^\\d{3}\\s?\\d{2}$')], verbose_name='PSČ')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Telefonní číslo')),
                ('membership', models.CharField(choices=[('A', 'aktivní'), ('P', 'přispívající')], default='A', max_length=2)),
                ('status', models.CharField(choices=[('PE', 'čeká na schválení'), ('AC', 'člen'), ('CA', 'zrušený')], default='PE', max_length=2)),
                ('comments', models.TextField(blank=True, verbose_name='Poznámky')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Uživatelský účet')),
            ],
            options={
                'verbose_name': 'historical Člen spolku',
                'verbose_name_plural': 'historical Členové spolku',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalStudent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('last_name', models.CharField(max_length=100, verbose_name='Příjmení')),
                ('birth_date', models.DateField(verbose_name='Datum narození')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='main.classcollective', verbose_name='Třída')),
            ],
            options={
                'verbose_name': 'historical Žák',
                'verbose_name_plural': 'historical Žáci',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
