# Generated by Django 6.0.6 on 2026-06-08 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemergerequest',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profilestudentrequest',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.profile'),
        ),
        migrations.AddField(
            model_name='student',
            name='parents',
            field=models.ManyToManyField(related_name='children', through='main.ParentRelationship', to='main.profile', verbose_name='Zákonní zástupci'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='main.classcollective', verbose_name='Třída'),
        ),
        migrations.AddField(
            model_name='profilestudentrequest',
            name='student_by_rc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student', verbose_name='Žák (ověřeno rodným číslem)'),
        ),
        migrations.AddField(
            model_name='profilemergerequest',
            name='student_by_rc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student', verbose_name='Žák (ověřeno rodným číslem)'),
        ),
        migrations.AddField(
            model_name='parentrelationship',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.student'),
        ),
        migrations.AddConstraint(
            model_name='parentrelationship',
            constraint=models.UniqueConstraint(fields=('student', 'parent'), name='student_parent_unique'),
        ),
    ]
