# Generated by Django 6.0.6 on 2026-08-16 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_create_vrmember_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemergerequest',
            name='birth_date',
        ),
        migrations.AlterField(
            model_name='profilemergerequest',
            name='student_by_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student', verbose_name='Přiřazený žák'),
        ),
    ]
