# Generated by Django 6.0.6 on 2026-08-16 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_profilemergerequest_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentrelationship',
            options={'verbose_name': 'Vztah rodič-žák', 'verbose_name_plural': 'Vztahy rodič-žák'},
        ),
        migrations.AlterModelOptions(
            name='profilemergerequest',
            options={'verbose_name': 'Žádost o sloučení účtů', 'verbose_name_plural': 'Žádosti o sloučení účtů'},
        ),
        migrations.AlterModelOptions(
            name='profilestudentrequest',
            options={'verbose_name': 'Žádost o přidání žáka', 'verbose_name_plural': 'Žádosti o přidání žáka'},
        ),
    ]
