# Generated by Django 6.0.6 on 2026-08-16 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_parentrelationship_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Datum podání žádosti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum podání žádosti'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilemergerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum podání'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilestudentrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Datum podání'),
            preserve_default=False,
        ),
    ]
