# Generated by Django 6.0.6 on 2026-08-16 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historicalprofile_created_at_profile_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRepresentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representant_type', models.CharField(choices=[('VR', 'zástupce ve VR'), ('P', 'pokladník')], max_length=20, verbose_name='Typ zástupce')),
                ('valid_from', models.DateField(auto_now=True, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.profile')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.classcollective')),
            ],
            options={
                'verbose_name': 'Zástupce třídy',
                'verbose_name_plural': 'Zástupci tříd',
            },
        ),
        migrations.AddField(
            model_name='classcollective',
            name='representatives',
            field=models.ManyToManyField(related_name='represented_classes', through='main.ClassRepresentative', to='main.profile', verbose_name='Zástupci třídy'),
        ),
        migrations.AddConstraint(
            model_name='classrepresentative',
            constraint=models.UniqueConstraint(fields=('school_class', 'representative', 'representant_type'), name='class_representative_unique'),
        ),
    ]
