# Generated by Django 6.0.6 on 2026-08-17 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_create_capoditutti_and_secretaryofthetreasury_groups'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcollective',
            options={'ordering': ['year', 'variant'], 'verbose_name': 'Třídna', 'verbose_name_plural': 'Třídy'},
        ),
    ]
