# Generated by Django 6.0.6 on 2026-08-17 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_classcollective_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='classrepresentative',
            name='class_representative_unique',
        ),
        migrations.AlterField(
            model_name='classrepresentative',
            name='valid_from',
            field=models.DateField(default=datetime.date.today, verbose_name='Platnost od'),
        ),
        migrations.AddConstraint(
            model_name='classrepresentative',
            constraint=models.UniqueConstraint(fields=('school_class', 'representative', 'representant_type', 'valid_until'), name='class_representative_unique'),
        ),
    ]
