# Generated by Django 6.1 on 2026-08-20 04:27

import datetime
import django.db.models.deletion
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_classrepresentative_class_representative_unique_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Stránky s libovolným z těchto tagů se zobrazí jako stránky kruhu.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tagy stránek')),
            ],
            options={
                'verbose_name': 'Kruh',
                'verbose_name_plural': 'Kruhy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CircleMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(default=datetime.date.today, verbose_name='Platnost od')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Platnost do')),
                ('speaker_of_circle', models.BooleanField(default=False, verbose_name='Mluvčí kruhu')),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.circle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.profile')),
            ],
            options={
                'verbose_name': 'Členství v kruhu',
                'verbose_name_plural': 'Členství v kruzích',
            },
        ),
        migrations.AddField(
            model_name='circle',
            name='members',
            field=models.ManyToManyField(related_name='circles', through='main.CircleMembership', to='main.profile', verbose_name='Členové'),
        ),
        migrations.CreateModel(
            name='HistoricalCircle',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jméno')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Kruh',
                'verbose_name_plural': 'historical Kruhy',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='circlemembership',
            constraint=models.UniqueConstraint(fields=('circle', 'profile', 'valid_until'), name='circle_membership_unique'),
        ),
    ]
