# Generated by Django 6.1 on 2026-08-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_circle_circlemembership_circle_members_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classcollective',
            options={'ordering': ['-year', 'variant'], 'verbose_name': 'Třídna', 'verbose_name_plural': 'Třídy'},
        ),
        migrations.AddConstraint(
            model_name='classcollective',
            constraint=models.UniqueConstraint(fields=('school_class', 'variant'), name='unique_class_collective_name2'),
        ),
    ]
