# Generated by Django 6.1 on 2026-09-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_create_kolegium_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprofile',
            name='phone_visible',
            field=models.BooleanField(default=True, verbose_name='Telefon viditelný ostatním členům'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_visible',
            field=models.BooleanField(default=True, verbose_name='Telefon viditelný ostatním členům'),
        ),
    ]
